### PR TITLE
Create AV1.md

### PR DESCRIPTION
**Pull request by amitmehrafullstack**

### CODE REVIEW

**Comment by saghul** [comment]
Can you please be a bit more detailed? AFAIK no browser currently ships an AV1 encoder, and the decoder is not usable from WebRTC so what the project consist on exactly?

**Comment by amitmehrafullstack** [comment]
Hello,
Thank you for the response
If this is in the roadmap anyway, in-case support is provided in Chrome and
Chromium

**Comment by saghul** [comment]
Yes it is. But unless a browser la da WebRTC support for it, we don’t have much to act upon. I’m going to close this because of the aforementioned reasons.

**Comment by EwoutH** [comment]
Some work on using AV1 with WebRTC has been done:
[Chromium/webrtc: Add Av1 Decoder wrapper behind a build flag](https://chromium.googlesource.com/external/webrtc/+/c46385c346d5a98b83ecef16bd4b4aa219a61d71)

**Pull request closed without merging**
