### PR TITLE
Create maximum-download-maximum-upload-text.md

### PR DESCRIPTION
**Pull request by amitmehrafullstack**

### CODE REVIEW

**Comment by saghul** [comment]
@bgrozev Can you comment if this is something we'd ever like to see implemented?

**Comment by bgrozev** [comment]
@amitmehrafullstack I don't understand the reasons for this. What problem does it solve and when/how do you expect to use it? Between estimating and adapting to the available bandwidth, limiting the number of video streams with LastN, and limiting the receive video resolution (the "Manage Video Quality" option in the web client) we should be covering most cases.

**Comment by amitmehrafullstack** [comment]
The aim is to have the ability to control the maximum download and upload
which should help in-case of connection slowness, currently based on the
resolution defined and the status of the connection the download and upload
speed will be calculated, which give us a volatile quality.

**Comment by bgrozev** [comment]
The current implementation is based on an estimation of the available bandwidth (not resolution).

**Pull request closed without merging**
