### PR TITLE
Add the speech-to-text project.

### PR DESCRIPTION
**Pull request by bgrozev**

### CODE REVIEW

**Comment by nikvaessen** [comment]
I already commited it!

**Comment by nikvaessen** [comment]
I like your reformat though

**Comment by bgrozev** [comment]
Is there anything I should pick up from your version?

**Comment by nikvaessen** [comment]
Leave an issue for any questions?

**Comment by bgrozev** [comment]
To clarify: this is all Nik's work, I was just porting it from his google doc

**Pull request merged**
